export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_ERROR = "PRODUCT_LIST_ERROR";

export const SET_PAGE = "SET_PAGE";
export const SET_KEYWORD = "SET_KEYWORD";
export const SET_CATEGORY = "SET_CATEGORY";
export const SET_TAGS = "SET_TAGS";
export const NEXT_PAGE = "NEXT_PAGE";
export const PREV_PAGE = "PREV_PAGE";
export const TOGGLE_TAG = "TOGGLE_TAG";

export const PRODUCT_DETAIL = "PRODUCT_DETAIL";
export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
